name: 'Setup Wiremock'
description: 'Setup a standalone Wiremock process with stubs defined in JSON files'
inputs:
  mappings:
    description: 'Path to folder with JSON stubs (as described in http://wiremock.org/docs/running-standalone/#json-file-configuration)'
    required: true
    default: 'wiremock-mappings'
  files:
    description: 'Path to folder with static files (as described in http://wiremock.org/docs/running-standalone/#json-file-configuration)'
    required: true
    default: 'wiremock-files'
  http-port:
    description: 'Port on which to run Wiremock'
    required: false
    default: '8080'
outputs:
  wiremock-stdout:
    description: 'Logs from Wiremock'
  wiremock-stderr:
    description: 'Errors from running Wiremock'
runs:
  using: 'node12'
  main: 'index.js'